################################################################################
# lib/libtk — common + sysdepend
################################################################################

# Common sources
SRC_DIR := lib/libtk
include $(MTKERNEL_ROOT)/config/rules.mk

# CPU layer
SRC_DIR := lib/libtk/sysdepend/cpu/$(CPU_DIR)
include $(MTKERNEL_ROOT)/config/rules.mk

# Core layer
SRC_DIR := lib/libtk/sysdepend/cpu/core/$(CORE_DIR)
include $(MTKERNEL_ROOT)/config/rules.mk
